config/routes.rb
Rails.application.routes.draw do
  resources :organizers
  resources :aulos
  resources :attendees

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
    validates :login, :phone_number, presence: true
    has_many :aulo_attendees_relationships
    has_many :aulos, :through  => :aulo_attendees_relationships
end

app/models/aulo.rb
class Aulo < ActiveRecord::Base
    validates :label, presence: true 
    belongs_to :organizer
    has_many :aulo_attendees_relationships
    has_many :attendees, :through  => :aulo_attendees_relationships
end

app/models/aulo_attendees_relationship.rb
class AuloAttendeesRelationship < ActiveRecord::Base
  belongs_to :aulo
  belongs_to :attendee
end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
    validates :login, :phone_number, presence: true
    has_many :aulos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: [:show, :edit, :update, :destroy]

  # GET /attendees
  # GET /attendees.json
  def index
    @attendees = Attendee.all
  end

  # GET /attendees/1
  # GET /attendees/1.json
  def show
  end

  # GET /attendees/new
  def new
    @attendee = Attendee.new
  end

  # GET /attendees/1/edit
  def edit
  end

  # POST /attendees
  # POST /attendees.json
  def create
    @attendee = Attendee.new(attendee_params)

    respond_to do |format|
      if @attendee.save
        format.html { redirect_to @attendee, notice: 'Attendee was successfully created.' }
        format.json { render :show, status: :created, location: @attendee }
      else
        format.html { render :new }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendees/1
  # PATCH/PUT /attendees/1.json
  def update
    respond_to do |format|
      if @attendee.update(attendee_params)
        format.html { redirect_to @attendee, notice: 'Attendee was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendee }
      else
        format.html { render :edit }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
  def destroy
    @attendee.destroy
    respond_to do |format|
      format.html { redirect_to attendees_url, notice: 'Attendee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendee_params
      params.require(:attendee).permit(:login, :phone_number)
    end
end

app/controllers/aulos_controller.rb
class AulosController < ApplicationController
  before_action :set_aulo, only: [:show, :edit, :update, :destroy]

  # GET /aulos
  # GET /aulos.json
  def index
    @aulos = Aulo.all
  end

  # GET /aulos/1
  # GET /aulos/1.json
  def show
  end

  # GET /aulos/new
  def new
    @aulo = Aulo.new
  end

  # GET /aulos/1/edit
  def edit
  end

  # POST /aulos
  # POST /aulos.json
  def create
    @aulo = Aulo.new(aulo_params)

    respond_to do |format|
      if @aulo.save
        NotificationJob.set(wait_until: @aulo.start_at - 10.minutes).perform_later(@aulo)
        format.html { redirect_to @aulo, notice: 'Aulo was successfully created.' }
        format.json { render :show, status: :created, location: @aulo }
      else
        format.html { render :new }
        format.json { render json: @aulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aulos/1
  # PATCH/PUT /aulos/1.json
  def update
    respond_to do |format|
      if @aulo.update(aulo_params)
        format.html { redirect_to @aulo, notice: 'Aulo was successfully updated.' }
        format.json { render :show, status: :ok, location: @aulo }
      else
        format.html { render :edit }
        format.json { render json: @aulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aulos/1
  # DELETE /aulos/1.json
  def destroy
    @aulo.destroy
    respond_to do |format|
      format.html { redirect_to aulos_url, notice: 'Aulo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aulo
      @aulo = Aulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aulo_params
      params.require(:aulo).permit(:label, :start_at, :organizer_id, attendee_ids: [])
    end
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
  before_action :set_organizer, only: [:show, :edit, :update, :destroy]

  # GET /organizers
  # GET /organizers.json
  def index
    @organizers = Organizer.all
  end

  # GET /organizers/1
  # GET /organizers/1.json
  def show
  end

  # GET /organizers/new
  def new
    @organizer = Organizer.new
  end

  # GET /organizers/1/edit
  def edit
  end

  # POST /organizers
  # POST /organizers.json
  def create
    @organizer = Organizer.new(organizer_params)

    respond_to do |format|
      if @organizer.save
        format.html { redirect_to @organizer, notice: 'Organizer was successfully created.' }
        format.json { render :show, status: :created, location: @organizer }
      else
        format.html { render :new }
        format.json { render json: @organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizers/1
  # PATCH/PUT /organizers/1.json
  def update
    respond_to do |format|
      if @organizer.update(organizer_params)
        format.html { redirect_to @organizer, notice: 'Organizer was successfully updated.' }
        format.json { render :show, status: :ok, location: @organizer }
      else
        format.html { render :edit }
        format.json { render json: @organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizers/1
  # DELETE /organizers/1.json
  def destroy
    @organizer.destroy
    respond_to do |format|
      format.html { redirect_to organizers_url, notice: 'Organizer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organizer
      @organizer = Organizer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organizer_params
      params.require(:organizer).permit(:login, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/aulos_helper.rb
module AulosHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/views/attendees/_form.html.erb
<%= form_for(@attendee) do |f| %>
  <% if @attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
      <% @attendee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendees/edit.html.erb
<h1>Editing Attendee</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendee %> |
<%= link_to 'Back', attendees_path %>

app/views/attendees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Attendees</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendees.each do |attendee| %>
      <tr>
        <td><%= attendee.login %></td>
        <td><%= attendee.phone_number %></td>
        <td><%= link_to 'Show', attendee %></td>
        <td><%= link_to 'Edit', edit_attendee_path(attendee) %></td>
        <td><%= link_to 'Destroy', attendee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendee', new_attendee_path %>

app/views/attendees/new.html.erb
<h1>New Attendee</h1>

<%= render 'form' %>

<%= link_to 'Back', attendees_path %>

app/views/attendees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @attendee.login %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @attendee.phone_number %>
</p>

<%= link_to 'Edit', edit_attendee_path(@attendee) %> |
<%= link_to 'Back', attendees_path %>

app/views/aulos/_form.html.erb
<%= form_for(@aulo) do |f| %>
  <% if @aulo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aulo.errors.count, "error") %> prohibited this aulo from being saved:</h2>

      <ul>
      <% @aulo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br>
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :organizer_id %><br>
    <%= f.collection_select :organizer_id, Organizer.all, :id, :login %>
  </div>  
  
  
<div class="param">

    <%= f.label :attendees %>

    <span class="ul">

	<% Attendee.all.each do |attendee| %>
	  <label class="li"><%= check_box_tag :attendee_ids, attendee.id, @aulo.attendees.include?(attendee), :name => 'aulo[attendee_ids][]' %> <u><%= attendee.login %></u></label><br />
	<% end %>

    </span>

</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aulos/edit.html.erb
<h1>Editing Aulo</h1>

<%= render 'form' %>

<%= link_to 'Show', @aulo %> |
<%= link_to 'Back', aulos_path %>

app/views/aulos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Aulos</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Start at</th>
      <th>Organizer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aulos.each do |aulo| %>
      <tr>
        <td><%= aulo.label %></td>
        <td><%= aulo.start_at %></td>
        <td><%= aulo.organizer.login %></td>
        <td><%= link_to 'Show', aulo %></td>
        <td><%= link_to 'Edit', edit_aulo_path(aulo) %></td>
        <td><%= link_to 'Destroy', aulo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aulo', new_aulo_path %>

app/views/aulos/new.html.erb
<h1>New Aulo</h1>

<%= render 'form' %>

<%= link_to 'Back', aulos_path %>

app/views/aulos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @aulo.label %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @aulo.start_at %>
</p>

<p>
  <strong>Organizer :</strong>
  <%= @aulo.organizer.login %>
</p>
<p>
  <strong>Attendees :</strong><br/>
  <% @aulo.attendees.each do |attendee| %>
    <%= attendee.login %><br/>
  <% end %>
</p>
<%= link_to 'Edit', edit_aulo_path(@aulo) %> |
<%= link_to 'Back', aulos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/organizers/_form.html.erb
<%= form_for(@organizer) do |f| %>
  <% if @organizer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organizer.errors.count, "error") %> prohibited this organizer from being saved:</h2>

      <ul>
      <% @organizer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizers/edit.html.erb
<h1>Editing Organizer</h1>

<%= render 'form' %>

<%= link_to 'Show', @organizer %> |
<%= link_to 'Back', organizers_path %>

app/views/organizers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organizers</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizers.each do |organizer| %>
      <tr>
        <td><%= organizer.login %></td>
        <td><%= organizer.phone_number %></td>
        <td><%= link_to 'Show', organizer %></td>
        <td><%= link_to 'Edit', edit_organizer_path(organizer) %></td>
        <td><%= link_to 'Destroy', organizer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organizer', new_organizer_path %>

app/views/organizers/new.html.erb
<h1>New Organizer</h1>

<%= render 'form' %>

<%= link_to 'Back', organizers_path %>

app/views/organizers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @organizer.login %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @organizer.phone_number %>
</p>

<%= link_to 'Edit', edit_organizer_path(@organizer) %> |
<%= link_to 'Back', organizers_path %>